language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: "4048f997d81e3e6868c8c65c77dbee6a585be085"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'